### PR TITLE
Tup#7

### PR DESCRIPTION
**Pull request by gdalyy**

### CODE REVIEW

**Comment by bumi** [comment]
I guess we have reviewed the code already? so we can merge it?

**Comment by gdalyy** [comment]
Yes i think so !

**Comment by gdalyy** [comment]
But in this case i think we should merge the PR without deleting the branch ( tup#7 )

**Comment by bumi** [comment]
why? as it is merged?

**Comment by gdalyy** [comment]
I think that we're still working on tup#7 while issue#7 is not resolved, we actually resolved some sub tasks of this issue

**Comment by bumi** [comment]
ok, 
though I'd suggest we create small branches/PRs for each little task and merge those separately.

**Comment by gdalyy** [comment]
Oh ok , as you wish :+1:

**Comment by bumi** [comment]
no, no. as you/we wish! 
that's just a suggestion... as branching is easy and it is easier to review small pieces. also it is easier to deploy small pieces. So I prefer to quickly iterate on small changes (instead of one big release)

**Comment by gdalyy** [comment]
Well, you're right , i agree :+1:

**Comment by gdalyy** [comment]
Anyway branch tup#7 is not deleted yet after you merged the tup#26 PR, because there is a open PR coming from tup#34 that depends on tup#7 !? Should we close that PR and delete tup#7 or change the base branch of this PR to master and then delete tup#7 ? What do you think ?

**Comment by gdalyy** [comment]
@bumi, @craxrev : Do you think that we need to close PR#34 branch or we just change its base branch to master so that we can delete tup#7 ?

**Comment by bumi** [comment]
you can also merge it locally/manually in master. 

but I think the main question there is if we merge that feature? and how we continue with the tasks modul?

**Comment by gdalyy** [comment]
I've already merged tup#7 into master locally.

I didn't say that we need to merge tup#34 PR into master, i meant since we deleted tup#7 from **x-coin module** after merging it into master , we should do the same thing here in **tasks module**, to achieve that and delete tup#7 branch here we need to close this  tup#34 PR or change its base branch to master without merging it.

**Comment by bumi** [comment]
ah ok. I think the branch would be created again once you merge or push into it. 
but yeah, let's change the base and merge it into master.

**Comment by gdalyy** [comment]
I think we don't need to merge it now since we don't fully agree about *Making an account creation optional** we should wait for Salem to discuss this issue first, besides master branch should now contains only tup#26 that we will deploy on the prod server.

But now we just need to change the base branch of this PR from tup#7 to master so that we can delete tup#7 branch like we did in **x-coin module**. 

If you agree, i'll change the base branch and delete tup#7 branch ! 
What do you think ?

**Comment by bumi** [comment]
sounds good!

**Comment by gdalyy** [comment]
Done :smiley:

**Pull request merged**
